version: "v1.0"
name: Basic YAML configuration file example.
semaphore_image: standard
blocks:
  - build:
      jobs:
        - name: My Semaphore 2.0 job
          commands:
            - echo $SECRET_ONE
            - echo $SEMAPHORE_PIPELINE_ID
            - echo "Hello World!"
            - echo $SECRET_TWO
      secrets:
        - name: mySecrets
          env_var_names: []
        - name: more-mihalis-secrets
          env_var_names: []

